import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  daiSuXanhSidebar: [{type: 'autogenerated', dirName: 'dai-su-xanh'}],
  nhaLapDatSidebar: [{type: 'autogenerated', dirName: 'nha-lap-dat'}],
  khachHangSidebar: [{type: 'autogenerated', dirName: 'khach-hang'}],
  hoTroSidebar: [{type: 'autogenerated', dirName: 'ho-tro'}],
};

export default sidebars;

