import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import {ambassadorGuideGroups} from './src/data/ambassadorContent';

const daiSuXanhSidebar = ambassadorGuideGroups.map((group) => ({
  type: 'category' as const,
  label: group.title,
  collapsible: true,
  collapsed: false,
  link: {
    type: 'generated-index' as const,
    title: group.title,
    slug: `/dai-su-xanh/${group.id}`,
  },
  items: group.topics.map((topic) => ({
    type: 'doc' as const,
    id: `dai-su-xanh/${topic.groupId}/${topic.id}/index`,
    label: topic.title,
  })),
}));

const sidebars: SidebarsConfig = {
  daiSuXanhSidebar,
  nhaLapDatSidebar: [{type: 'autogenerated', dirName: 'nha-lap-dat'}],
  khachHangSidebar: [{type: 'autogenerated', dirName: 'khach-hang'}],
  hoTroSidebar: [{type: 'autogenerated', dirName: 'ho-tro'}],
};

export default sidebars;

